import { useEffect, useState } from 'react';
import { ApiError, serviceApi } from '../api/client';
import { Field, Modal } from '../components/ui';
import limits from './serviceRateFields.json';
import { today, addMonths } from '../lib/format';
import RateUpload from '../components/RateUpload';
export type ServiceRate = { id: number; revision: number; type: string; recordType: string; rateType: string; chargeType: string; validFrom: string; validTo: string; isActive: boolean } & Record<string, string | number | boolean | null>;
const label = (s: string) => s.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase()).replace('Uom', 'unit').replace('Salesforce Opportunity Id', 'Salesforce opportunity ID');
const names: Record<string, string> = { Customs: 'Customs', Trucking: 'Trucking', CrossBorder: 'X-border' };
const msg = (e: unknown) => e instanceof Error ? e.message : 'Request failed.';
export default function ServiceRatesPage({ category }: { category: 'customs' | 'transport' }) {
 const [rows, setRows] = useState<ServiceRate[]>([]), [total, setTotal] = useState(0), [page, setPage] = useState(1);
 const [search, setSearch] = useState(''), [type, setType] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(false);
 const [upload,setUpload]=useState(false),[notice,setNotice]=useState('');
 const [editing, setEditing] = useState<ServiceRate | null>(null);
 async function load() { setLoading(true); setError(''); try { const data = await serviceApi.list(category, type, search, page); setRows(data.items); setTotal(data.total); } catch(e) { setError(msg(e)); } finally { setLoading(false); } }
 useEffect(() => { void load(); }, [category, type, page]);
 const money = (r: ServiceRate, side: string) => r[`${side}Amount`] == null ? 'Not set' : `${r[`${side}Currency`]} ${r[`${side}Amount`]} / ${r[`${side}Uom`]}`;
 return <><h1>{category === 'customs' ? 'Customs tariffs' : 'Transport tariffs'}</h1><p className="subtitle">{category === 'customs' ? 'Customs clearance and related service charges.' : 'Trucking and cross-border charges in one table, grouped by type.'} Each row is one charge; buying cost and selling price retain their own currency, minimum and unit.</p>
 {notice && <div className="banner info">{notice}</div>}
 {error && <div role="alert" className="banner error">{error}</div>}
 <div className="card"><form className="toolbar" onSubmit={e => { e.preventDefault(); if (page !== 1) setPage(1); else void load(); }}>
 <Field label="Search"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Charge, vendor, customer or route" /></Field>
 {category === 'transport' && <Field label="Type"><select value={type} onChange={e => { setType(e.target.value); setPage(1); }}><option value="">All transport</option><option value="Trucking">Trucking</option><option value="CrossBorder">X-border</option></select></Field>}
 <button disabled={loading}>{loading ? 'Loading…' : 'Search / refresh'}</button><span className="spacer" /><button type="button" onClick={()=>setUpload(true)}>Upload rates</button><button type="button" className="primary" onClick={() => setEditing({ id: 0, revision: 0, type: category === 'customs' ? 'Customs' : type || 'Trucking', recordType: 'General', rateType: 'FAK', chargeType: 'Mandatory', validFrom: today(), validTo: addMonths(today(), 3), isActive: true, owner: 'WICEBKK', costCurrency: 'THB', costUom: 'Trip' })}>Add charge rate</button></form>
 <div style={{ overflowX: 'auto' }}><table><thead><tr>{['Type', 'Vendor / agent', 'Route', 'Charge code', 'Charge', 'Buying cost', 'Selling price', 'Minimum cost / sell', 'Validity', 'Record', 'Status', 'Actions'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>
 {rows.map(r => <tr key={r.id}><td><span className="tag">{names[r.type]}</span></td><td>{r.vendor || '—'}</td><td>{r.originLocation || r.portOfLoading || r.originCountry || '—'} → {r.destinationLocation || r.portOfDestination || r.destinationCountry || r.port || '—'}</td><td>{r.chargeCode}</td><td>{r.chargeItem}<div className="muted">{r.chargeType}</div></td><td>{money(r, 'cost')}</td><td>{money(r, 'sell')}</td><td>{r.costMinimum ?? '—'} / {r.sellMinimum ?? '—'}</td><td>{r.validFrom}<br />{r.validTo}</td><td>{r.recordType}<div className="muted">{r.customerCode || r.customerName || ''}</div></td><td>{r.isActive ? 'Active' : 'Inactive'}</td><td><button type="button" onClick={() => setEditing(structuredClone(r))}>Edit</button> <button type="button" className="danger" onClick={async () => { if (!confirm('Delete this charge rate?')) return; try { await serviceApi.remove(r.id, r.revision); await load(); } catch(e) { setError(msg(e)); } }}>Delete</button></td></tr>)}
 {!loading && !rows.length && <tr><td colSpan={12}>No charge rates found. Add a rate to get started.</td></tr>}
 </tbody></table></div><div className="row" style={{ marginTop: 16 }}><span>{total} rates · Page {page}</span><span className="spacer" /><button disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</button><button disabled={page * 50 >= total} onClick={() => setPage(p => p + 1)}>Next</button></div></div>
 {upload && <RateUpload kinds={category==='customs'?['Customs']:['Trucking','CrossBorder']} onClose={()=>setUpload(false)} onSaved={message=>{setUpload(false);setNotice(message);void load();}} />}
 {editing && <Editor initial={editing} category={category} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); }} />}</>;
}
function Editor({ initial, category, onClose, onSaved }: { initial: ServiceRate; category: string; onClose: () => void; onSaved: () => Promise<void> }) {
 const [form, setForm] = useState(initial), [saving, setSaving] = useState(false), [error, setError] = useState('');
 const set = (key: string, value: string | number | boolean | null) => setForm(f => ({ ...f, [key]: value }));
 const input = (key: string, required = false) => <Field key={key} label={key === 'vendor' && category === 'customs' ? 'Agent' : label(key)}><input required={required} maxLength={limits[key as keyof typeof limits]} value={String(form[key] ?? '')} onChange={e => set(key, e.target.value || null)} /></Field>;
 const select = (key: string, values: string[]) => <Field label={label(key)}><select value={String(form[key] ?? '')} onChange={e => set(key, e.target.value)}>{values.map(v => <option key={v} value={v}>{names[v] || v}</option>)}</select></Field>;
 async function save(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(''); try { await serviceApi.save(form); await onSaved(); } catch(e) { setError(e instanceof ApiError ? `${e.message} ${Object.values(e.fieldErrors).flat().join(' ')}` : msg(e)); } finally { setSaving(false); } }
 const location = ['Country','Province','City','Location','Postcode'];
 return <Modal title={`${initial.id ? 'Edit' : 'Add'} ${category === 'customs' ? 'customs' : 'transport'} charge rate`} onClose={() => { if (!saving) onClose(); }}><form onSubmit={save}><fieldset disabled={saving} style={{ border: 0, padding: 0 }}>
 {error && <div className="banner error" role="alert">{error}</div>}
 <h2>Rate details</h2><div className="grid">{category === 'transport' && select('type', ['Trucking','CrossBorder'])}{input('owner', true)}{input('vendor')}{select('recordType', ['General','RFQ'])}{select('rateType', ['FAK','NAC'])}{input('customerCode', form.recordType === 'RFQ' || form.rateType === 'NAC')}{input('customerName')}{input('salesforceOpportunityId', form.recordType === 'RFQ')}
 {['validFrom','validTo'].map(key => <Field key={key} label={label(key)}><input type="date" required value={String(form[key])} onChange={e => set(key, e.target.value)} /></Field>)}</div>
 <h2 style={{ marginTop: 20 }}>Service and route</h2><div className="grid">
 {category === 'customs' ? ['shippingLine','shipmentType','direction','containerType','portOfReceipt','portOfLoading','portOfDischarge','portOfDestination','originCountry','destinationCountry'].map(k => input(k)) : <>{['service','direction','truckType','cargoType','port'].map(k => input(k))}{location.map(k => input(`origin${k}`, k === 'Country' && form.type === 'CrossBorder'))}{location.map(k => input(`destination${k}`, k === 'Country' && form.type === 'CrossBorder'))}<Field label="Fuel price reference"><input type="number" min={0} step="0.01" value={String(form.fuelPrice ?? '')} onChange={e => set('fuelPrice', e.target.value === '' ? null : Number(e.target.value))} /></Field></>}
 </div><p className="small muted">For trucking, retain the port separately. Use origin and destination locations for domestic routes. Fuel price is a reference value; no fuel adjustment is calculated.</p>
 <h2>Charge</h2><p className="small muted">Leave charge code blank to derive it from the quotation template or charge name. Review inferred codes before use.</p><div className="grid">{input('chargeCode')}{input('chargeItem', true)}{select('chargeType', ['Mandatory','Subject','Optional'])}</div>
 {['cost','sell'].map(side => <section key={side} style={{ marginTop: 20 }}><h2>{side === 'cost' ? 'Buying cost' : 'Selling price'}</h2><div className="grid">{input(`${side}Currency`, side === 'cost')}{['Minimum','Amount'].map(k => <Field key={k} label={k}><input type="number" min={0} max={999999999} step="0.01" required={side === 'cost' && k === 'Amount'} value={String(form[side+k] ?? '')} onChange={e => set(side+k, e.target.value === '' ? null : Number(e.target.value))} /></Field>)}{input(`${side}Uom`, side === 'cost')}</div><Field label="Remark"><textarea rows={2} maxLength={1000} value={String(form[`${side}Remark`] ?? '')} onChange={e => set(`${side}Remark`, e.target.value || null)} /></Field></section>)}
 <p className="small muted">Units can include shipment, container, container/day, or trip. These service tables store prices; freight inquiries do not calculate or add these charges yet.</p><label><input type="checkbox" checked={form.isActive} onChange={e => set('isActive', e.target.checked)} /> Active</label><div className="row" style={{ marginTop: 20, justifyContent: 'flex-end' }}><button type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">{saving ? 'Saving…' : 'Save charge rate'}</button></div>
 </fieldset></form></Modal>;
}
