import { useEffect, useState } from 'react';
import { PortInput } from './Ports';
import { CountryInput } from './Countries';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from './ui/table';
import { rateImportApi, stagedImportApi } from '../api/client';
import { Field, Modal, Spinner } from './ui';
export type UploadKind = 'SeaFcl' | 'SeaLcl' | 'Air' | 'Customs' | 'Trucking' | 'CrossBorder';
export type PortReviewChoice = {line:number;field:string;code:string;carrier?:string;remember:boolean};
export interface RateImportPreview {
 token:string; expiresAtUtc:string; created:number;updated:number;
 portResolutions?:{sourceLine:number;field:string;originalValue:string;resolvedCodes:string;mapping:string;carrier:string}[];
 rows:{line:number;action:string;key:string;type:string;carrier:string|null;origin:string|null;destination:string|null;chargeCode:string;charge:string;cost:number|null;costBySize?:Record<string,number|null>|null;priceBySize?:Record<string,number|null>|null;costCurrency:string;costUnit:string;price:number|null;priceCurrency:string|null;priceUnit:string|null;validFrom:string;validTo:string;recordType:string;accountId:string|null;details:unknown}[];
}

export type StagedRow={rowId:number;sourceLine:number;status:string;reasonCode:string|null;reason:string|null;revision:number;attempts:number;importedAtUtc:string|null;values:Record<string,string>;portMappings?:{field:string;originalValue:string;code:string}[];originalCells:string[];result:unknown};
export type StagedUpload={uploadId:string;kind:UploadKind;fileName:string;status:string;reasonCode:string|null;reason:string|null;revision:number;mappedSource?:boolean;headers:string[];originalHeaders:string[];columns:string[];counts:{status:string;count:number}[];total:number;page:number;pageSize:number;rows:StagedRow[]};
export type ImportHistory={items:{uploadId:string;kind:UploadKind;fileName:string;status:string;reasonCode:string|null;reason:string|null;createdAtUtc:string;total:number;success:number;failed:number}[];total:number;page:number;pageSize:number};
const names:Record<UploadKind,string>={SeaFcl:'Sea FCL',SeaLcl:'Sea LCL',Air:'Air freight',Customs:'Customs',Trucking:'Trucking',CrossBorder:'Cross-border'};
const portFields=['PortOfReceipt','PortOfLoading','PortOfDischarge','PortOfDestination','Port','TsPort'];
export default function RateUpload({kinds,onClose,onSaved}:{kinds:UploadKind[];onClose:()=>void;onSaved:(message:string)=>void}) {
 const [kind,setKind]=useState<UploadKind>(kinds[0]);const [history,setHistory]=useState<ImportHistory|null>(null);
 const [upload,setUpload]=useState<StagedUpload|null>(null);const [filter,setFilter]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [dirty,setDirty]=useState(false);
 const [remember,setRemember]=useState<string[]>([]);
 const [editing,setEditing]=useState<StagedRow|null>(null);const [values,setValues]=useState<Record<string,string>>({});const [headers,setHeaders]=useState<string[]|null>(null);
 const message=(e:unknown)=>e instanceof Error?e.message:'Import request failed.';
 useEffect(()=>{let active=true;void stagedImportApi.list(kind).then(x=>{if(active)setHistory(x);}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;};},[kind]);
 async function run(action:()=>Promise<void>) {setBusy(true);setError('');try{await action();}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function refreshHistory(page=1) {setHistory(await stagedImportApi.list(kind,page));}
 async function open(id:string,page=1,status='') {setUpload(await stagedImportApi.detail(id,page,status));setFilter(status);setEditing(null);setHeaders(null);}
 async function chooseFile(file:File) {await run(async()=>{setUpload(await stagedImportApi.upload(kind,file));setFilter('');setEditing(null);setHeaders(null);await refreshHistory();});}
 async function process(commit:boolean) {if(!upload)return;await run(async()=>{setUpload(await stagedImportApi.process(upload.uploadId,commit));setFilter('');if(commit)setDirty(true);await refreshHistory();});}
 async function saveRow() {if(!upload||!editing)return;await run(async()=>{setUpload(await stagedImportApi.edit(upload.uploadId,editing.rowId,editing.revision,values,remember));setEditing(null);setFilter('');await refreshHistory();});}
 const close=()=>{if(!busy){if(dirty)onSaved('Import results saved. Failed rows remain available in upload history.');else onClose();}};
 const count=(status:string)=>upload?.counts.find(c=>c.status===status)?.count??0;
 const unfinished=upload?.counts.filter(c=>c.status!=='Success').reduce((sum,c)=>sum+c.count,0)??0;
 const columns=upload?[...new Set([...upload.headers.map((h,i)=>h||`Column ${i+1}`),...upload.rows.flatMap(r=>Object.keys(r.values))])]:[];
 return <Modal title="Rate uploads and corrections" onClose={close}>
  <div className="toolbar"><Field label="Service type"><select aria-label="Upload service type" value={kind} disabled={busy} onChange={e=>{setKind(e.target.value as UploadKind);setUpload(null);setEditing(null);setHeaders(null);setError('');setHistory(null);}}>{kinds.map(k=><option key={k} value={k}>{names[k]}</option>)}</select></Field>
   <Button variant="outline" disabled={busy} onClick={()=>void run(()=>rateImportApi.download(kind,false))}>Download blank template</Button><Button variant="outline" disabled={busy} onClick={()=>void run(()=>rateImportApi.download(kind,true))}>Download existing rates</Button>
  </div>
  <p>Upload CSV or the first sheet of an XLSX workbook (5 MB / 5,000 rows). The original file and input columns are kept in import history. Uploading the identical file again reopens its saved results. Dates use yyyy-mm-dd or Excel dates; upload values without formulas.</p>
  <p className="small muted">Ready rows have passed validation but are not imported yet. Success means the rate was saved. Correct failed rows and retry; successful rows are skipped. All charge rows for the same freight rate are processed together. Country, port and carrier mappings are applied on each attempt, including multi-port splitting.</p>
  <Field label="Choose file"><Input aria-label="Rate file" type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void chooseFile(file);e.target.value='';}}/></Field>
  {error&&<div className="banner error" role="alert">{error}</div>}{busy&&<Spinner label="Processing import…"/>}
  <details open={!upload}><summary>Upload history ({history?.total??0})</summary><Button variant="outline" disabled={busy} onClick={()=>void run(()=>refreshHistory())}>Refresh upload history</Button>
   <Table><TableHeader><TableRow>{['File','Uploaded','Status','Rows','Success','Failed',''].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{history?.items.map(item=><TableRow key={item.uploadId}><TableCell>{item.fileName}</TableCell><TableCell>{new Date(item.createdAtUtc).toLocaleString()}</TableCell><TableCell>{item.status}</TableCell><TableCell>{item.total}</TableCell><TableCell>{item.success}</TableCell><TableCell>{item.failed}</TableCell><TableCell><Button variant="outline" disabled={busy} onClick={()=>void run(()=>open(item.uploadId))}>Open upload</Button></TableCell></TableRow>)}</TableBody></Table>
   {history&&history.total>history.pageSize&&<div className="toolbar"><Button disabled={busy||history.page===1} onClick={()=>void run(()=>refreshHistory(history.page-1))}>Previous uploads</Button><span>Page {history.page}</span><Button disabled={busy||history.page*history.pageSize>=history.total} onClick={()=>void run(()=>refreshHistory(history.page+1))}>Next uploads</Button></div>}
  </details>
  {upload&&<section style={{marginTop:20}}><h3>{upload.fileName}</h3><p role="status">{count('Ready')} ready · {count('Success')} success · {count('Failed')} failed · {count('Pending')} pending</p>
   {upload.reason&&<div className="banner error">{upload.reasonCode}: {upload.reason}{upload.reasonCode==='FILE_PARSE_ERROR'&&<p>The original file is retained. Fix the file and upload a new copy.</p>}</div>}
   <div className="toolbar"><Button variant="outline" disabled={busy} onClick={()=>void run(()=>stagedImportApi.original(upload.uploadId,upload.fileName))}>Download original file</Button>
    <Button variant="outline" disabled={busy||count('Success')>0||upload.mappedSource||!upload.headers.length} onClick={()=>{setHeaders([...upload.headers]);setEditing(null);}}>Correct column names</Button>
    <Button variant="outline" disabled={busy||!unfinished||!!editing||!!headers} onClick={()=>void process(false)}>Validate unfinished rows</Button>
    <Button disabled={busy||!unfinished||!!editing||!!headers} onClick={()=>void process(true)}>Import / retry unfinished rows</Button>
   </div>
   {headers&&<div style={{padding:16,border:'1px solid #ddd'}}><h4>Correct file columns</h4><p>Rename columns to template names. Original headings and values remain in the saved file.</p><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}>{headers.map((header,i)=><Field key={i} label={`Column ${i+1} (original: ${upload.originalHeaders[i]||'blank'})`}><Input list="import-column-names" value={header} disabled={busy} onChange={e=>setHeaders(old=>old!.map((h,n)=>n===i?e.target.value:h))}/></Field>)}</div><datalist id="import-column-names">{upload.columns.map(c=><option key={c} value={c}/>)}</datalist><div className="toolbar"><Button disabled={busy} onClick={()=>void run(async()=>{setUpload(await stagedImportApi.headers(upload.uploadId,upload.revision,headers));setHeaders(null);setFilter('');await refreshHistory();})}>Save column names</Button><Button variant="outline" disabled={busy} onClick={()=>setHeaders(null)}>Cancel column changes</Button></div></div>}
   {editing&&<div style={{padding:16,border:'1px solid #ddd'}}><h4>Correct Excel row {editing.sourceLine}</h4>{editing.reason&&<p role="alert">{editing.reasonCode}: {editing.reason}</p>}
    <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}>{Object.entries(values).map(([column,value])=><Field key={column} label={column}>{portFields.includes(column)?<PortInput field={column} mode={upload.kind} ariaLabel={column} country={column==='PortOfLoading'||column==='PortOfReceipt'?values.OriginCountry:column==='PortOfDestination'?values.DestCountry??values.DestinationCountry:undefined} value={value} disabled={busy} onChange={v=>setValues(old=>({...old,[column]:v}))}/>:column.endsWith('Country')?<CountryInput value={value} onChange={v=>setValues(old=>({...old,[column]:v}))}/>:<Input aria-label={column} value={value} disabled={busy} onChange={e=>setValues(old=>({...old,[column]:e.target.value}))}/>}</Field>)}</div>
    {['SeaFcl','SeaLcl','Air'].includes(upload.kind)&&<div><p className="small muted">Optionally reuse a corrected port for this carrier on future uploads. The mapping is saved with a successful import; include a Carrier value.</p>{portFields.filter(f=>f in values).map(field=><label key={field} style={{display:'block'}}><input type="checkbox" disabled={busy} checked={remember.includes(field)} onChange={e=>setRemember(old=>e.target.checked?[...old,field]:old.filter(f=>f!==field))}/> Remember carrier mapping for {field}{editing.portMappings?.find(m=>m.field===field)?` (${editing.portMappings.find(m=>m.field===field)!.originalValue})`:''}</label>)}</div>}
    <div><p className="small muted">For an alternative port name used by all carriers, select its standard location above, then save a shared alias. This immediately retries affected failed rates across upload history; successful rows are skipped.</p>{portFields.filter(field=>editing.values[field]?.trim() && /^[A-Z]{2}[A-Z0-9]{3}$/.test(values[field]??'') && values[field]!==editing.values[field]).map(field=><Button key={field} variant="outline" disabled={busy} onClick={()=>void run(async()=>{setUpload(await stagedImportApi.sharedAlias(upload.uploadId,editing.rowId,editing.revision,field,values[field]));setEditing(null);setFilter('');setDirty(true);await refreshHistory();})}>Remember “{editing.values[field]}” → {values[field]} for all carriers in {values[field].slice(0,2)} and retry</Button>)}</div>
    <Field label="Add an omitted column"><select aria-label="Add an omitted column" disabled={busy} value="" onChange={e=>{if(e.target.value)setValues(old=>({...old,[e.target.value]:''}));}}><option value="">Choose column</option>{upload.columns.filter(c=>!(c in values)).map(c=><option key={c} value={c}>{c}</option>)}</select></Field>
    <p className="small muted">Saving corrections keeps the original values and does not change live rates. Then validate or retry the unfinished rows. Keep repeated rate details consistent across its charge rows.</p>
    <div className="toolbar"><Button disabled={busy} onClick={()=>void saveRow()}>Save corrections</Button><Button variant="outline" disabled={busy} onClick={()=>setEditing(null)}>Cancel correction</Button></div>
   </div>}
   <Field label="Row status"><select aria-label="Row status" disabled={busy||!!editing||!!headers} value={filter} onChange={e=>void run(()=>open(upload.uploadId,1,e.target.value))}>{['','Failed','Ready','Pending','Success'].map(s=><option key={s} value={s}>{s||'All rows'}</option>)}</select></Field>
   <div style={{maxHeight:'45vh',overflow:'auto'}}><Table><TableHeader><TableRow>{['Excel row','Status','Action','Reason code','Reason',...columns].map((h,i)=><TableHead key={i} style={{whiteSpace:'nowrap'}}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{upload.rows.map(row=><TableRow key={row.rowId}><TableCell>{row.sourceLine}</TableCell><TableCell>{row.status}<div className="small muted">{row.attempts} import attempts</div></TableCell><TableCell>{row.status!=='Success'?<Button variant="outline" disabled={busy||!!editing||!!headers} onClick={()=>{setEditing(row);setValues({...row.values});setRemember(row.portMappings?.map(m=>m.field)??[]);}}>Correct row {row.sourceLine}</Button>:<span>Imported</span>}<details><summary>Original / result</summary><pre style={{maxWidth:400,whiteSpace:'pre-wrap'}}>{JSON.stringify({originalHeaders:upload.originalHeaders,originalCells:row.originalCells,result:row.result},null,2)}</pre></details></TableCell><TableCell>{row.reasonCode||'—'}</TableCell><TableCell style={{minWidth:220}}>{row.reason||'—'}</TableCell>{columns.map(c=><TableCell key={c} style={{whiteSpace:'nowrap'}}>{row.values[c]??''}</TableCell>)}</TableRow>)}</TableBody></Table></div>
   <div className="toolbar"><Button variant="outline" disabled={busy||upload.page===1||!!editing||!!headers} onClick={()=>void run(()=>open(upload.uploadId,upload.page-1,filter))}>Previous rows</Button><span>Page {upload.page} · {upload.total} matching rows</span><Button variant="outline" disabled={busy||upload.page*upload.pageSize>=upload.total||!!editing||!!headers} onClick={()=>void run(()=>open(upload.uploadId,upload.page+1,filter))}>Next rows</Button></div>
  </section>}
  <div className="toolbar" style={{marginTop:16}}><div className="spacer"/><Button disabled={busy} onClick={close}>Done</Button></div>
 </Modal>;
}
